### ISSUE TITLE
ISSUE: grunt-contrib-uglify raises an error on signature_pad

### ISSUE THREAD

**Issue by inakrin** [szimek/signature_pad#272]
Running "uglify:jsbower" (uglify) task
{ SyntaxError: Unexpected token: keyword (const)
    at JS_Parse_Error.get (eval at <anonymous> (/home/vagrant/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at formatError (util.js:644:15)
    at formatValue (util.js:550:18)
    at inspect (util.js:183:10)
    at exports.format (util.js:69:24)
    at Console.log (console.js:43:37)
    at /home/vagrant/node_modules/grunt-contrib-uglify/tasks/uglify.js:144:17
    at Array.forEach (native)
    at Object.<anonymous> (/home/vagrant/node_modules/grunt-contrib-uglify/tasks/uglify.js:78:16)
    at Object.<anonymous> (/home/vagrant/node_modules/grunt/lib/grunt/task.js:264:15)
  message: 'Unexpected token: keyword (const)',
  filename: 'bower.js',
  line: 167215,
  col: 0,
  pos: 5534369 }
>> Uglifying source data/static/build/bower.js failed.
Warning: Uglification failed.
Unexpected token: keyword (const). 
Line 167215 in data/static/build/bower.js
 Use --force to continue.

Aborted due to warnings.

This is probably due to this issue. Don't know what to do with it. https://github.com/gruntjs/grunt-contrib-uglify/issues/477

**Comment by szimek** [comment]
I'm not really sure what this issue has to do with this library, but:
1. Bower is no longer supported since version 1.5.x (the current one is 2.2.0)
2. Try to tell grunt to minify the version of the library compiled to ES5 - UglifyJS doesn't work yet with ES6 code.
