### ISSUE TITLE
signature_pad.mjs no such file or directory

### ISSUE THREAD

**Issue by surendra-17** [szimek/signature_pad#489]
Failed to compile.

./node_modules/signature_pad/dist/signature_pad.mjs
Module build failed: Error: ENOENT: no such file or directory, open '/Users/deep/Documents/hybrid/approach-info-app/node_modules/signature_pad/dist/signature_pad.mjs'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Storage.provideSync (/Users/deep/Documents/hybrid/approach-info-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/Users/deep/Documents/hybrid/approach-info-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable._subscribe (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@ngtools/webpack/src/compiler_host.js:147:44)
    at VirtualFileSystemDecorator.readFile (/Users/deep/Documents/hybrid/approach-info-app/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:42:54)
    at processResource (/Users/deep/Documents/hybrid/approach-info-app/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/Users/deep/Documents/hybrid/approach-info-app/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/Users/deep/Documents/hybrid/approach-info-app/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/Users/deep/Documents/hybrid/approach-

**Comment by cjinghong** [comment]
I'm facing the same issue

**Comment by alok-srivastav** [comment]
Same Issue

**Comment by UziTech** [comment]
closing as stale
